### PR TITLE
Don't require old version of react-native

### PR DESCRIPTION
**Pull request by 3bola**
This causes errors in newer versions

### CODE REVIEW

**Comment by JeanLebrument** [comment]
Please @t4t5 accept this pull request, I took so much time to understand from where the runtime error occurred on my project. At the end I discovered that it was due to react-native-router that uses an old react-native version.

**Comment by t4t5** [comment]
Quick merge :) Will have time to go through this project next week to fix things!

**Comment by JeanLebrument** [comment]
:+1:

**Comment by yarax** [comment]
Could you please say when it's going to be a new version of library with this fix?

**Comment by robtg4** [comment]
yeah @t4t5 this is urgent! lol

**Pull request merged**
