### PR TITLE
Use peerDependencies instead of dependencies for react-native

### PR DESCRIPTION
**Pull request by erichigg**
@t4t5, I am loving the react-native-router.  Had some problems today with react-native 0.6.0 and took a stab at correcting them.  Not sure if this is how you want to go with it but would rather send a PR than just report a problem.

Used approach from here: https://github.com/alinz/react-native-navbar/commit/0d4715e92331086c9c7fda3f041d61199a34b58f

Thanks,

Eric

### CODE REVIEW

**Comment by tylermcginnis** [comment]
This would be great. Currently holding off on using the Router because of this issue.

**Comment by irony** [comment]
please merge this..

**Comment by helielson** [comment]
+1

**Comment by helielson** [comment]
A pull request with this change already was proposed
#42

**Comment by erichigg** [comment]
Forgot about this and decided to close since #42 exists.

**Pull request closed without merging**
